apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "ui-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ui-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ui-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{  .Values.container.name }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.examplemap }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }} 
          ports:
            - containerPort: {{ .Values.service.targetport }}
