apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
  - name: mongodb
    port: {{ .Values.mongodb.service.port }}
    targetPort: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}