apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mongodb.pvc" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mongodb.pvc.storage }}
