apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "mongodb.secrets" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  db-user: {{ .Values.mongodb.dbuser.value | quote   }}
  db-password: {{ .Values.mongodb.dbpassword.value | quote   }}
  #db-password: echo {{ .Values.mongodb.dbpassword.value }} | base64
