apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  serviceName: database
  replicas: {{ .Values.mysql.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "mysql.name" . }}
        image: {{ .Values.mysql.deployment.image }}
        ports:
        - name: mysql
          containerPort: 27017
        env:
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.secrets" . }}
              key: db-user
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.secrets" . }}
              key: db-password 
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mongodb
      volumes:
      - name: db-data
        #persistentVolumeClaim:
         # claimName: {{ template "mysql.pvc" . }}