
namespace: demo-application
replicaCount: 1

image:
  repository: wordpress:4.8-apache
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion. 
  tag: ""

service:
  type: NodePort
  port: 80
  targetport: 80
  #ANNOTATIONS: {
  #  app.kubernetes.io/managed-by: Helm,
  #  meta.helm.sh/release-name: testapachepht,
  #  meta.helm.sh/release-namespace: demo-app-ns
  #}

container:
  name: myappcon
examplemap:
 - name: "DB_PASSWORD"
   value: "password" 
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  
