apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "postgres.secrets" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  db-password: {{ .Values.postgres.dbpassword.value | quote   }}
  #db-password: echo {{ .Values.postgres.dbpassword.value }} | base64
