apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
  - name: postgres
    port: {{ .Values.postgres.service.port }}
    targetPort: postgres
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}