apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgres.pvc" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
